

name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          build-root-directory: app
      - name: Test & publish code coverage
        # Publish code coverage on Code Climate
        # https://github.com/paambaati/codeclimate-action
        uses: paambaati/codeclimate-action@v3.0.0
        # Add Code Climate secret key
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        #with:
         # coverageCommand: make test-coverage
          #debug: true
      #  - name: Publish code coverage
      #uses: paambaati/codeclimate-action@v3.0.0
      #env:
      #  MYSECRET: ${{ secrets.SECRET_TOKEN }}
         #- name: Publish code coverage
      #uses: paambaati/codeclimate-action@v3.0.0
      #env:
       #  CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
      #   JACOCO_SOURCE_PATH: app/src/main/java
      #with:
      #   coverageCommand: make report
      #   coverageLocations: ${{github.workspace}}/app/build/jacocoReport/test/jacocoTestReport.xml:jacoco
      
      # - name: Publish code coverage
      #   uses: paambaati/codeclimate-action@v3.0.0
      #   env:
      #     CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
      #     JACOCO_SOURCE_PATH: src/main/java
      #   with:
      #     coverageCommand: make report
      #     coverageLocations: ${{github.workspace}}/build/reports/jacoco/test/jacocoTestReport.xml:jacoco